name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: "postgres:13"
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
        - elixir: '1.11.4'
          otp: '23.3'
        - elixir: '1.14.5'
          otp: '24.3'
#         - elixir: '1.15.0'
#           otp: '26.0.1'
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
          version-type: strict
      - name: Install Dependencies
        run: mix deps.get --only test
      - run: mix format --check-formatted
        if: ${{ matrix.lint }}
      - run: mix deps.get && mix deps.unlock --check-unused
        if: ${{ matrix.lint }}
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: MIX_ENV=test mix db.reset
      - run: mix test
